### ISSUE TITLE
Bug in Anson's optimization code

### ISSUE THREAD

**Issue by IlanIwumbwe** [chinjyanson/SmartGrid#14]
This always happens between the 50th and 60th tick. So probably your code doesn't correctly handle the case when you don't have enough values to fill up the window.

Error Message 
```
Current tick 51
Running Ansons Code
[{'end': 59, 'energy': 50.0, 'start': 0}, {'end': 59, 'energy': 22.244256002982212, 'start': 49}, {'end': 59, 'energy': 42.49201443240214, 'start': 49}]
  Get Energy In: 0.0 kWh
  Get Energy Used: 4.7069383608558795 kWh
  Get Buy Price: 82 £/kWh
  Get Sell Price: 164 £/kWh
Traceback (most recent call last):
  File "/home/ilan/Desktop/SmartGrid/buy-sell-algorithm/main2.py", line 175, in <module>
    algo.driver()
  File "/home/ilan/Desktop/SmartGrid/buy-sell-algorithm/main2.py", line 161, in driver
    time_taken = self.something_else()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilan/Desktop/SmartGrid/buy-sell-algorithm/main2.py", line 129, in something_else
    opt.maximize_profit_mpc(0, 50, self.data_buffers, self.predictions, self.tick)
  File "/home/ilan/Desktop/SmartGrid/buy-sell-algorithm/optimization.py", line 58, in maximize_profit_mpc
    profit = cp.sum(cp.multiply(neg_energy_transactions, predicted_sell_prices[t:t + horizon]) - cp.multiply(pos_energy_transactions, predicted_buy_prices[t:t + horizon]))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/atoms/affine/binary_operators.py", line 244, in __init__
    super(multiply, self).__init__(lh_expr, rh_expr)
  File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/atoms/affine/binary_operators.py", line 53, in __init__
    super(BinaryOperator, self).__init__(lh_exp, rh_exp)
  File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/atoms/atom.py", line 51, in __init__
    self._shape = self.shape_from_args()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/atoms/affine/binary_operators.py", line 281, in shape_from_args
    return u.shape.sum_shapes([arg.shape for arg in self.args])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/utilities/shape.py", line 50, in sum_shapes
    raise ValueError(
ValueError: Cannot broadcast dimensions  (10,) (9,)
```

**Comment by chinjyanson** [comment]
> This always happens between the 50th and 60th tick. So probably your code doesn't correctly handle the case when you don't have enough values to fill up the window.
> 
> Error Message
> 
> ```
> Current tick 51
> Running Ansons Code
> [{'end': 59, 'energy': 50.0, 'start': 0}, {'end': 59, 'energy': 22.244256002982212, 'start': 49}, {'end': 59, 'energy': 42.49201443240214, 'start': 49}]
>   Get Energy In: 0.0 kWh
>   Get Energy Used: 4.7069383608558795 kWh
>   Get Buy Price: 82 £/kWh
>   Get Sell Price: 164 £/kWh
> Traceback (most recent call last):
>   File "/home/ilan/Desktop/SmartGrid/buy-sell-algorithm/main2.py", line 175, in <module>
>     algo.driver()
>   File "/home/ilan/Desktop/SmartGrid/buy-sell-algorithm/main2.py", line 161, in driver
>     time_taken = self.something_else()
>                  ^^^^^^^^^^^^^^^^^^^^^
>   File "/home/ilan/Desktop/SmartGrid/buy-sell-algorithm/main2.py", line 129, in something_else
>     opt.maximize_profit_mpc(0, 50, self.data_buffers, self.predictions, self.tick)
>   File "/home/ilan/Desktop/SmartGrid/buy-sell-algorithm/optimization.py", line 58, in maximize_profit_mpc
>     profit = cp.sum(cp.multiply(neg_energy_transactions, predicted_sell_prices[t:t + horizon]) - cp.multiply(pos_energy_transactions, predicted_buy_prices[t:t + horizon]))
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/atoms/affine/binary_operators.py", line 244, in __init__
>     super(multiply, self).__init__(lh_expr, rh_expr)
>   File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/atoms/affine/binary_operators.py", line 53, in __init__
>     super(BinaryOperator, self).__init__(lh_exp, rh_exp)
>   File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/atoms/atom.py", line 51, in __init__
>     self._shape = self.shape_from_args()
>                   ^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/atoms/affine/binary_operators.py", line 281, in shape_from_args
>     return u.shape.sum_shapes([arg.shape for arg in self.args])
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/ilan/Desktop/SmartGrid/.venv/lib/python3.11/site-packages/cvxpy/utilities/shape.py", line 50, in sum_shapes
>     raise ValueError(
> ValueError: Cannot broadcast dimensions  (10,) (9,)
> ```

Resolved
